// File generated by FlutterFire configuration logic for Kalika
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBL8hp5Sc3xJ_WYSoRFFq9GqI8RcJOv4R0',
    appId: '1:346682434600:android:220e3aa67f6774b9f3411d',
    messagingSenderId: '346682434600',
    projectId: 'kalika-27e2e',
    storageBucket: 'kalika-27e2e.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBL8hp5Sc3xJ_WYSoRFFq9GqI8RcJOv4R0',
    appId: '1:346682434600:web:220e3aa67f6774b9f3411d',
    messagingSenderId: '346682434600',
    projectId: 'kalika-27e2e',
    storageBucket: 'kalika-27e2e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBL8hp5Sc3xJ_WYSoRFFq9GqI8RcJOv4R0',
    appId: '1:346682434600:ios:220e3aa67f6774b9f3411d',
    messagingSenderId: '346682434600',
    projectId: 'kalika-27e2e',
    storageBucket: 'kalika-27e2e.firebasestorage.app',
    iosBundleId: 'com.kalika.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBL8hp5Sc3xJ_WYSoRFFq9GqI8RcJOv4R0',
    appId: '1:346682434600:ios:220e3aa67f6774b9f3411d',
    messagingSenderId: '346682434600',
    projectId: 'kalika-27e2e',
    storageBucket: 'kalika-27e2e.firebasestorage.app',
    iosBundleId: 'com.kalika.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBL8hp5Sc3xJ_WYSoRFFq9GqI8RcJOv4R0',
    appId: '1:346682434600:web:220e3aa67f6774b9f3411d',
    messagingSenderId: '346682434600',
    projectId: 'kalika-27e2e',
    storageBucket: 'kalika-27e2e.firebasestorage.app',
  );
}
